# Buildspec runs in the build stage of your pipeline.
# Replace the values as needed
version: 0.2
phases:
  pre_build:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR/"
      - cd $CODEBUILD_SRC_DIR
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 570580688935.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t webapp .
      - docker tag webapp:latest 570580688935.dkr.ecr.ca-central-1.amazonaws.com/webapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push 570580688935.dkr.ecr.ca-central-1.amazonaws.com/webapp:latest
      - cd $CODEBUILD_SRC_DIR
      - echo "imagedefinitions.json > [{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json
      - printf "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json
env:
  variables:
    # Replace the value with your AWS account ID
    AWS_ACCOUNT_ID: 570580688935 
    # Replace the value with your AWS region - eg: us-east-1
    AWS_DEFAULT_REGION: ca-central-1 
    # Replace the value with the container name - eg: webapp
    CONTAINER_NAME: webapp
    IMAGE_URL: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    # Replace the value with the container image name:tag - eg: webapp:latest
    REPO_NAME: webapp:latest
artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/start_app.sh
    - scripts/stop_app.sh
  discard-paths: no
  name: '.'
    

